# Tasca S12.01. APIs REST

#### Descripció
Aplicaràs el que has après sobre APIs REST, mètodes HTTP i codis d'estat, utilitzant APIs públiques per consultar dades, filtrar-les i finalment desar-les en un DataFrame de pandas.

Recursos:

Nivell 1:

{JSON} Placeholder

Nivell 2:

Try Public APIs for free

Nivell 3:

Open Data BCN

## Nivell 1

Des d’un Jupyter Notebook faràs els següents exercicis utilitzant la llibreria requests de Python.

Exploració bàsica amb una API de laboratori.

In [1]:
import requests

### 1. Consulta l’API pública JSONPlaceholder utilitzant el mètode GET per obtenir:

- Llista de publicacions (/posts)
- Llista d’usuaris (/users)
- Llista de tasques (/todos)

In [3]:
base_url = "https://jsonplaceholder.typicode.com"

# GET Posts

posts_response = requests.get(f"{base_url}/posts")

# GET Users

users_response = requests.get(f"{base_url}/users")

# GET Todos

todos_response = requests.get(f"{base_url}/todos")

### 2. Mostra per pantalla:

- La quantitat total de cada recurs.
- El codi d'estat de cada petició.

In [4]:

# Convert JSON responses
posts = posts_response.json()
users = users_response.json()
todos = todos_response.json()

print("POSTS")
print(f"Total resources: {len(posts)}")
print(f"Status code: {posts_response.status_code}")

print("\nUSERS")
print(f"Total resources: {len(users)}")
print(f"Status code: {users_response.status_code}")

print("\nTODOS")
print(f"Total resources: {len(todos)}")
print(f"Status code: {todos_response.status_code}")

POSTS
Total resources: 100
Status code: 200

USERS
Total resources: 10
Status code: 200

TODOS
Total resources: 200
Status code: 200

### 3. Fes una petició a una publicació inexistent per obtenir un error 404 i mostra el codi d'estat rebut.

In [5]:
not_found_response = requests.get(f"{base_url}/posts/999999")

print("NON-EXISTENT POST")
print(f"Status code: {not_found_response.status_code}")

NON-EXISTENT POST
Status code: 404

### 4. Fes una petició POST per crear una nova publicació fictícia. Inclou el títol, el cos del missatge i un userId.

- Mostra la resposta JSON.
- Mostra el codi d'estat.

In [6]:
new_post = {
    "title": "My First API Post",
    "body": "This is a test post created with Requests.",
    "userId": 1
}

post_response = requests.post(
    f"{base_url}/posts",
    json=new_post
)

print("POST REQUEST")
print(f"Status code: {post_response.status_code}")

print("\nJSON Response:")
print(post_response.json())

POST REQUEST
Status code: 201

JSON Response:
{'title': 'My First API Post', 'body': 'This is a test post created with Requests.', 'userId': 1, 'id': 101}

### 5. Fes una petició PATCH per modificar parcialment una publicació existent.

- Mostra la resposta JSON.
- Mostra el codi d'estat.

In [7]:
updated_data = {
    "title": "Updated Title"
}

patch_response = requests.patch(
    f"{base_url}/posts/1",
    json=updated_data
)

print("PATCH REQUEST")
print(f"Status code: {patch_response.status_code}")

print("\nJSON Response:")
print(patch_response.json())

PATCH REQUEST
Status code: 200

JSON Response:
{'userId': 1, 'id': 1, 'title': 'Updated Title', 'body': 'quia et suscipit\nsuscipit recusandae consequuntur expedita et cum\nreprehenderit molestiae ut ut quas totam\nnostrum rerum est autem sunt rem eveniet architecto'}

### 6. Fes una petició DELETE sobre una publicació.

- Mostra la resposta JSON.
- Mostra el codi d'estat.

In [8]:
delete_response = requests.delete(
    f"{base_url}/posts/1"
)

print("DELETE REQUEST")
print(f"Status code: {delete_response.status_code}")

print("\nJSON Response:")
print(delete_response.json())

DELETE REQUEST
Status code: 200

JSON Response:
{}

## Nivell 2

Interacció amb una API pública real

API seleccionada: Open-Meteo

https://open-meteo.com/

### Ejercicio 1

Se ha seleccionado la API pública Open-Meteo.

Elijo esta porque conoceerla y dominarla me irá muy bien para cuando tenga que reahacer el proyecto final durante el verano!

Open-Meteo es una API meteorológica gratuita que permite realizar peticiones GET para obtener información sobre previsiones meteorológicas, temperaturas, precipitaciones, velocidad del viento y otros datos climáticos.

La API devuelve los resultados en formato JSON y no requiere autenticación para consultas básicas.

### Ejercicio 2

#### Endpoint 1

Forecast API

https://api.open-meteo.com/v1/forecast

Permite obtener previsiones meteorológicas para una ubicación determinada.

---

#### Endpoint 2

Marine Weather API

https://marine-api.open-meteo.com/v1/marine

Permite consultar información meteorológica marina.

---

#### Parámetros opcionales interesantes

##### latitude

Latitud de la ubicación.

Ejemplo:

latitude=41.3888

---

##### longitude

Longitud de la ubicación.

Ejemplo:

longitude=2.159

---

##### current

Permite solicitar variables meteorológicas actuales.

Ejemplo:

current=temperature_2m

---

##### hourly

Permite solicitar variables horarias.

Ejemplo:

hourly=temperature_2m

---

#### Formato de respuesta

La API devuelve la información en formato JSON.

### 3. Fes una petició GET senzilla:

- Mostra el codi d'estat de la resposta.
- Imprimeix de forma clara alguns dels camps de la resposta JSON.

In [2]:
import requests
import pandas as pd

In [3]:
url = (
    "https://api.open-meteo.com/v1/forecast"
    "?latitude=41.3888"
    "&longitude=2.159"
    "&current=temperature_2m,relative_humidity_2m,wind_speed_10m"
)

response = requests.get(url)

print(f"Status code: {response.status_code}")

Status code: 200

In [4]:
data = response.json()

print("Latitude:", data["latitude"])
print("Longitude:", data["longitude"])

print("\nCurrent Weather Data")

print(
    f"Temperature: {data['current']['temperature_2m']} °C"
)

print(
    f"Relative Humidity: {data['current']['relative_humidity_2m']} %"
)

print(
    f"Wind Speed: {data['current']['wind_speed_10m']} km/h"
)

Latitude: 41.375
Longitude: 2.125

Current Weather Data
Temperature: 23.7 °C
Relative Humidity: 71 %
Wind Speed: 1.8 km/h

### 4. Converteix les dades a un DataFrame de pandas:

Mostra les primeres files del DataFrame.

In [5]:
hourly_url = (
    "https://api.open-meteo.com/v1/forecast"
    "?latitude=41.3888"
    "&longitude=2.159"
    "&hourly=temperature_2m"
)

hourly_response = requests.get(hourly_url)

hourly_data = hourly_response.json()

In [6]:
weather_df = pd.DataFrame({
    "time": hourly_data["hourly"]["time"],
    "temperature": hourly_data["hourly"]["temperature_2m"]
})

weather_df.head()

               time  temperature
0  2026-06-17T00:00         21.8
1  2026-06-17T01:00         21.6
2  2026-06-17T02:00         21.4
3  2026-06-17T03:00         21.0
4  2026-06-17T04:00         21.0

## Nivell 3
API d'Open Data Barcelona

### 1. Utilitza l’API d’Open Data BCN per:

- Cercar un dataset del teu interès mitjançant package_search i package_show. .

Dataset seleccionado:

Metadades de les estacions meteorològiques

https://opendata-ajuntament.barcelona.cat/data/ca/dataset/metadades-estacions-meteorologiques

### 2. Dels resultats obtinguts, selecciona’n un que tingui recursos disponibles en CSV o JSON.

In [7]:
import requests
import pandas as pd

In [8]:
search_url = (
    "https://opendata-ajuntament.barcelona.cat/data/api/3/action/package_search"
)

params = {
    "q": "estacions meteorologiques"
}

search_response = requests.get(search_url, params=params)

print(f"Status code: {search_response.status_code}")

Status code: 200

### 3. Amb el resource_id del recurs seleccionat, realitza una consulta mitjançant datastore_search per:

Recuperar almenys 100 registres.

In [9]:
search_data = search_response.json()

print("Datasets encontrados:")
print()

for dataset in search_data["result"]["results"][:5]:
    print(dataset["title"])

Datasets encontrados:

Metadata  list  of  meteorological stations of the city of Barcelona
Statistical resources of the meteorological stations of the city of Barcelona
Meteorological stations of the city of Barcelona

In [10]:
dataset_id = search_data["result"]["results"][0]["name"]

show_url = (
    "https://opendata-ajuntament.barcelona.cat/data/api/3/action/package_show"
)

show_response = requests.get(
    show_url,
    params={"id": dataset_id}
)

print(f"Status code: {show_response.status_code}")

Status code: 200

In [11]:
dataset_info = show_response.json()

print("Título:")
print(dataset_info["result"]["title"])

print("\nNúmero de recursos:")
print(len(dataset_info["result"]["resources"]))

Título:
Metadata  list  of  meteorological stations of the city of Barcelona

Número de recursos:
1

### 4. Converteix els resultats a un DataFrame.

In [12]:
csv_url = (
    "https://opendata-ajuntament.barcelona.cat/data/"
    "dataset/feafec8a-b389-42b5-a85d-cf16f3976440/resource/"
    "feafec8a-b389-42b5-a85d-cf16f3976440/download/"
    "2020_meteocat_estacions.csv"
)

df = pd.read_csv(csv_url)

In [13]:
df.head()

,CODI_ESTACIO,NOM_ESTACIO,EMPLACAMENT,CODI_BARRI,NOM_BARRI,CODI_DISTRICTE,NOM_DISTRICTE,CODI_MUNICIPI,NOM_MUNICIPI,CODI_COMARCA,...,NOM_PROVINCIA,ALTITUD,LATITUD,LONGITUD,CODI_XARXA,NOM_XARXA,CODI_ESTAT,DATA_ALTA,DATA_BAIXA,ACRÒNIM
0,D5,Barcelona - Observatori Fabra,Observatori Fabra,22,"Vallvidrera, el Tibidabo i les Planes",5,Sarrià-Sant Gervasi,80193,Barcelona,13,...,Barcelona,411,41.41864,2.12379,1,XEMA,2,1995-11-03,NaN,DVM10
1,D5,Barcelona - Observatori Fabra,Observatori Fabra,22,"Vallvidrera, el Tibidabo i les Planes",5,Sarrià-Sant Gervasi,80193,Barcelona,13,...,Barcelona,411,41.41864,2.12379,1,XEMA,2,1995-11-03,NaN,DVVX10
2,D5,Barcelona - Observatori Fabra,Observatori Fabra,22,"Vallvidrera, el Tibidabo i les Planes",5,Sarrià-Sant Gervasi,80193,Barcelona,13,...,Barcelona,411,41.41864,2.12379,1,XEMA,2,1995-11-03,NaN,HRM
3,D5,Barcelona - Observatori Fabra,Observatori Fabra,22,"Vallvidrera, el Tibidabo i les Planes",5,Sarrià-Sant Gervasi,80193,Barcelona,13,...,Barcelona,411,41.41864,2.12379,1,XEMA,2,1995-11-03,NaN,HRN
4,D5,Barcelona - Observatori Fabra,Observatori Fabra,22,"Vallvidrera, el Tibidabo i les Planes",5,Sarrià-Sant Gervasi,80193,Barcelona,13,...,Barcelona,411,41.41864,2.12379,1,XEMA,2,1995-11-03,NaN,HRX

In [14]:
print(f"Total records: {len(df)}")

Total records: 51

### 5. Desa el DataFrame en un fitxer .csv.

In [15]:
df.to_csv(
    "meteo_estacions_barcelona.csv",
    index=False
)

print("CSV file saved successfully")

CSV file saved successfully