# Getting Started with characters & strings

In [10]:
import pandas as pd
import numpy as np

In [5]:
#__string = "He said, \"Datacamp\"" 
__string = "He said, 'Datacamp'" # Las 2 opciones son validas para no tener errores y poder poner entr ""
print(__string)

He said, 'Datacamp'

In [6]:
"beekepers".split("e")

['b', '', 'k', 'p', 'rs']

# Getting started with DataFrames

In [11]:
# Create DataFrame from Dictionary
pd.DataFrame({
    'a': [1, 2, 3],
    'b': np.array([4, 4, 6]),
    'c': ['x', 'x', 'y']
})

   a  b  c
0  1  4  x
1  2  4  x
2  3  6  y

In [16]:
# Create a DataFrame from a list of dictionaries

df = pd.DataFrame([
    {'a': 1, 'b': 4, 'c': 'x'},
    {'a': 1, 'b': 4, 'c': 'x'},
    {'a': 4, 'b': 6, 'c': 'y'},
])
df

   a  b  c
0  1  4  x
1  1  4  x
2  4  6  y

### Selecting DataFrame Elements

In [18]:
df.iloc[2]

a    4
b    6
c    y
Name: 2, dtype: object

In [20]:
df['b']

0    4
1    4
2    6
Name: b, dtype: int64

In [30]:
df.loc[2,'b']

np.int64(6)

In [22]:
df[['a', 'c']]

   a  c
0  1  x
1  1  x
2  4  y

### Manipulating DataFrames

In [23]:
#Concatenate Vertically
pd.concat([df, df])

   a  b  c
0  1  4  x
1  1  4  x
2  4  6  y
0  1  4  x
1  1  4  x
2  4  6  y

In [24]:
# Concatenate horizontally
pd.concat([df, df], axis = 'columns')

   a  b  c  a  b  c
0  1  4  x  1  4  x
1  1  4  x  1  4  x
2  4  6  y  4  6  y

In [ ]:
# add a new column
df.assign(temp_f=9 / 5 + 32)

   a  b  c  temp_f
0  1  4  x    33.8
1  1  4  x    33.8
2  4  6  y    33.8